name: doorcode_nfc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.9
  firebase_core: ^2.29.0
  get: ^4.6.6
  cloud_firestore: ^4.16.1
  geolocator: ^7.7.0
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.9
  local_auth: ^2.2.0
  firebase_storage: ^11.7.1
  path: ^1.9.0
  nfc_manager: ^3.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/email.png
    - assets/phone.png
    - assets/user.png
    - assets/hestia.png
    - assets/proshow.png
    - assets/hestia2.png
    - assets/nexera.png
    - assets/nfc.png
    - assets/password.png
    - assets/home (4).png
    - assets/ticket (1) 1.png
    - assets/user (3) 1.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - assets/ADD_IMAGE.png
    - assets/home-1.png
    - assets/home new.png
    - assets/ticket new.png
    - assets/ticket.png
    - assets/profile.png
    - assets/yourevents.png
    - assets/listurshow.png
    - assets/logout.png
    - assets/accountinfo.png
    - assets/microphone.png
    - assets/clubs.png
    - assets/standup.png
    - assets/sports.png
  


  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
