// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfMR8FNQd1S_cod24GpCFjtjvpnmmViR0',
    appId: '1:548944456332:web:6f279c32fc9041a5f7a9a9',
    messagingSenderId: '548944456332',
    projectId: 'doorcode-23c79',
    authDomain: 'doorcode-23c79.firebaseapp.com',
    storageBucket: 'doorcode-23c79.appspot.com',
    measurementId: 'G-JQTXY6ZWZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9m8KPJuBYENv1v4Cduob4epAuXJGb0g',
    appId: '1:548944456332:android:e0f5aeb2fd37ce62f7a9a9',
    messagingSenderId: '548944456332',
    projectId: 'doorcode-23c79',
    storageBucket: 'doorcode-23c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_igSwL-Vkl28Dr4GcLBRwVkB-ZGuBPSE',
    appId: '1:548944456332:ios:18912eb4095b45dcf7a9a9',
    messagingSenderId: '548944456332',
    projectId: 'doorcode-23c79',
    storageBucket: 'doorcode-23c79.appspot.com',
    iosBundleId: 'com.example.doorcodeNfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_igSwL-Vkl28Dr4GcLBRwVkB-ZGuBPSE',
    appId: '1:548944456332:ios:cb34d4c83660635bf7a9a9',
    messagingSenderId: '548944456332',
    projectId: 'doorcode-23c79',
    storageBucket: 'doorcode-23c79.appspot.com',
    iosBundleId: 'com.example.doorcodeNfc.RunnerTests',
  );
}
